// ============================================================================
// Rollease SDK — Flag Type Code Generator
// ============================================================================
//
// Generates TypeScript declaration files that augment the `FlagDefinitions`
// interface, giving compile-time type safety for flag keys across the SDK.
//
// Usage:
//
//   // From DB (server-side, build script, or CLI):
//   import { generateFlagTypesFromDb } from 'rollease/codegen'
//   const dts = await generateFlagTypesFromDb(db)
//   fs.writeFileSync('rollease.d.ts', dts)
//
//   // From exported JSON:
//   import { generateFlagTypesFromJson } from 'rollease/codegen'
//   const dts = generateFlagTypesFromJson('./flags-export.json')
//
//   // Directly from flag objects:
//   import { generateFlagTypes } from 'rollease/codegen'
//   const dts = generateFlagTypes(flags)
//
// ============================================================================

import type { Flag, FlagType } from "../core/types";
import type { DbAdapter } from "../db/adapter";

// ── Internal helpers ──────────────────────────────────────────────────────────

/**
 * Map a Rollease FlagType to a TypeScript type string for code generation.
 */
function flagTypeToTSString(type: FlagType): string {
  switch (type) {
    case "boolean":
      return "boolean";
    case "string":
      return "string";
    case "number":
      return "number";
    case "json":
      return "Record<string, unknown>";
    case "multivariate":
      return "unknown";
    case "percentage":
      return "boolean";
    default:
      return "unknown";
  }
}

/**
 * Serialize a default value to a TypeScript literal string.
 */
function serializeDefaultValue(value: unknown): string {
  if (value === null || value === undefined) return "undefined";
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  // Objects/arrays — inline as type-narrowed literals
  return JSON.stringify(value);
}

/**
 * Escape a flag key for use as a TypeScript string literal property.
 */
function escapeKey(key: string): string {
  // If the key is a simple identifier, no quotes needed in the interface.
  // But since flag keys typically use hyphens/dots, always use string literals.
  return JSON.stringify(key);
}

// ── Codegen output formatting ─────────────────────────────────────────────────

const BANNER = `// ============================================================================
// Auto-generated by \`rollease codegen\` — DO NOT EDIT
//
// Re-run \`npx rollease codegen\` after creating or changing flag definitions.
// This file provides compile-time type safety for flag keys.
// ============================================================================
`;

interface CodegenFlag {
  key: string;
  type: FlagType;
  defaultValue: unknown;
  description?: string;
}

/**
 * Generate a `.d.ts` file body that augments `rollease/core/types`
 * with the given flag definitions.
 *
 * @param flags Array of flag objects (only `key`, `type`, `defaultValue`, and `description` are used).
 * @returns A TypeScript declaration file string.
 */
export function generateFlagTypes(
  flags: Array<Pick<Flag, "key" | "type" | "defaultValue" | "description">>
): string {
  const entries = flags
    .slice()
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((f) => {
      const tsType = flagTypeToTSString(f.type);
      const defaultVal = serializeDefaultValue(f.defaultValue);
      const comment = f.description
        ? `    /** ${f.description} */\n`
        : "";
      return `${comment}    ${escapeKey(f.key)}: { type: '${f.type}'; defaultValue: ${defaultVal} };`;
    })
    .join("\n");

  return `${BANNER}
declare module 'rollease/core/types' {
  interface FlagDefinitions {
${entries}
  }
}

// Also augment the root 'rollease' module re-export
declare module 'rollease' {
  interface FlagDefinitions {
${entries}
  }
}

export {};
`;
}

/**
 * Read a JSON file containing exported flag definitions and generate
 * a typed flag registry.
 *
 * The JSON file should be an array of objects with at minimum:
 * `{ key: string; type: FlagType; defaultValue: unknown }`
 *
 * @param filePath Absolute or relative path to the JSON file.
 * @returns A TypeScript declaration file string.
 */
export function generateFlagTypesFromJson(filePath: string): string {
  // Dynamic require for Node.js environments.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  let data: unknown;
  try {
    // Use dynamic import-like pattern that works in both CJS and ESM.
    // We read the file synchronously since codegen is a build-time tool.
    const fs = require("fs") as typeof import("fs");
    const raw = fs.readFileSync(filePath, "utf-8");
    data = JSON.parse(raw);
  } catch (err) {
    throw new Error(
      `Failed to read flag definitions from "${filePath}": ${
        (err as Error).message
      }`
    );
  }

  const flags = normalizeJsonInput(data);
  return generateFlagTypes(flags);
}

/**
 * Read all flags from a database adapter and generate a typed flag registry.
 *
 * @param db A Rollease DbAdapter instance.
 * @returns A TypeScript declaration file string.
 */
export async function generateFlagTypesFromDb(
  db: DbAdapter
): Promise<string> {
  const allFlags: CodegenFlag[] = [];
  let offset = 0;
  const limit = 1000;

  while (true) {
    const page = await db.getAllActiveFlags({ limit, offset });
    for (const flag of page) {
      allFlags.push({
        key: flag.key,
        type: flag.type,
        defaultValue: flag.defaultValue,
        description: flag.description,
      });
    }
    if (page.length < limit) break;
    offset += page.length;
  }

  // Also include killed/archived flags so the type registry covers the
  // full flag surface — users may reference killed flags in test code.
  const killed = await db.listFlags({ status: "killed" });
  for (const flag of killed.data) {
    if (!allFlags.some((f) => f.key === flag.key)) {
      allFlags.push({
        key: flag.key,
        type: flag.type,
        defaultValue: flag.defaultValue,
        description: flag.description,
      });
    }
  }

  const archived = await db.listFlags({ status: "archived" });
  for (const flag of archived.data) {
    if (!allFlags.some((f) => f.key === flag.key)) {
      allFlags.push({
        key: flag.key,
        type: flag.type,
        defaultValue: flag.defaultValue,
        description: flag.description,
      });
    }
  }

  return generateFlagTypes(allFlags);
}

// ── JSON normalization ────────────────────────────────────────────────────────

function normalizeJsonInput(data: unknown): CodegenFlag[] {
  // Accept array of flag objects
  if (Array.isArray(data)) {
    return data.map(normalizeJsonFlag).filter(Boolean) as CodegenFlag[];
  }

  // Accept object with a `flags` key (common export format)
  if (
    typeof data === "object" &&
    data !== null &&
    "flags" in data &&
    Array.isArray((data as { flags: unknown }).flags)
  ) {
    return ((data as { flags: unknown[] }).flags)
      .map(normalizeJsonFlag)
      .filter(Boolean) as CodegenFlag[];
  }

  // Accept object keyed by flag key (flat format)
  if (typeof data === "object" && data !== null) {
    return Object.entries(data as Record<string, unknown>)
      .map(([key, val]) => {
        if (typeof val === "object" && val !== null && "type" in val) {
          const flagObj = val as Record<string, unknown>;
          return {
            key,
            type: String(flagObj.type) as FlagType,
            defaultValue: flagObj.defaultValue ?? flagObj.value,
            description: flagObj.description as string | undefined,
          };
        }
        // Simple key → value map: infer type from value
        return {
          key,
          type: inferFlagType(val),
          defaultValue: val,
        };
      });
  }

  throw new Error(
    "Invalid JSON format: expected an array of flags, { flags: [...] }, or { key: value } map"
  );
}

function normalizeJsonFlag(item: unknown): CodegenFlag | null {
  if (typeof item !== "object" || item === null) return null;
  const obj = item as Record<string, unknown>;
  const key = obj.key as string;
  if (!key || typeof key !== "string") return null;

  return {
    key,
    type: (obj.type as FlagType) ?? inferFlagType(obj.defaultValue ?? obj.value),
    defaultValue: obj.defaultValue ?? obj.value,
    description: obj.description as string | undefined,
  };
}

function inferFlagType(value: unknown): FlagType {
  if (typeof value === "boolean") return "boolean";
  if (typeof value === "number") return "number";
  if (typeof value === "string") return "string";
  if (typeof value === "object" && value !== null) return "json";
  return "boolean";
}
