// ============================================================================
// Rollease SDK — Typed Flag Key Infrastructure
// ============================================================================
//
// This module provides compile-time type safety for flag keys.  When users
// augment the `FlagDefinitions` interface (either manually or via codegen),
// all flag access methods — `evaluate()`, `isEnabled()`, `useFlag()`, etc. —
// narrow their return types automatically.
//
// ## How it works
//
// 1. **Without augmentation**: `FlagDefinitions` is empty, so `TypedFlagKey`
//    falls back to `string`.  Everything works like an untyped SDK.
//
// 2. **With augmentation** (manual or codegen):
//
//    ```ts
//    // rollease.d.ts  (generated by `rollease codegen`)
//    declare module 'rollease/core/types' {
//      interface FlagDefinitions {
//        'checkout-v2':    { type: 'boolean'; defaultValue: false };
//        'pricing-layout': { type: 'string';  defaultValue: 'vertical' };
//        'max-items':      { type: 'number';  defaultValue: 25 };
//        'theme-config':   { type: 'json';    defaultValue: { mode: 'dark' } };
//      }
//    }
//    ```
//
//    Now `rl.flags.isEnabled('checkout-v2', ctx)` compiles, but
//    `rl.flags.isEnabled('chekout-v2', ctx)` is a type error.
//
// ============================================================================

/**
 * Flag type definitions registry.
 *
 * Users augment this interface to get compile-time flag key validation and
 * return-type narrowing across the entire SDK surface.
 *
 * Leave empty for untyped usage (all flag methods accept `string`).
 */
export interface FlagDefinitions {
  // Augmented by user code or `rollease codegen`:
  // 'my-flag': { type: 'boolean'; defaultValue: false };
}

// ── Type-level helpers ─────────────────────────────────────────────────────

/**
 * When `FlagDefinitions` has been augmented, resolves to the union of its
 * keys.  When empty, falls back to `string` for full backward compatibility.
 */
export type TypedFlagKey = keyof FlagDefinitions extends never
  ? string
  : Extract<keyof FlagDefinitions, string>;

/**
 * Check if FlagDefinitions has been augmented (i.e. is non-empty).
 */
export type HasFlagDefinitions = keyof FlagDefinitions extends never
  ? false
  : true;

// ── Flag type → TS type mapping ────────────────────────────────────────────

/** Map a Rollease FlagType string to its TypeScript value type. */
export type FlagTypeToTS<T extends string> = T extends 'boolean'
  ? boolean
  : T extends 'string'
    ? string
    : T extends 'number'
      ? number
      : T extends 'json'
        ? Record<string, unknown>
        : T extends 'multivariate'
          ? unknown
          : T extends 'percentage'
            ? boolean
            : unknown;

/**
 * Resolve the TypeScript value type for a given flag key.
 *
 * When `FlagDefinitions` is augmented:
 *   `FlagValueType<'checkout-v2'>` → `boolean`
 *   `FlagValueType<'pricing-layout'>` → `string`
 *
 * When `FlagDefinitions` is empty:
 *   `FlagValueType<string>` → `unknown`
 */
export type FlagValueType<K extends string> =
  K extends keyof FlagDefinitions
    ? FlagDefinitions[K] extends { type: infer T extends string }
      ? FlagTypeToTS<T>
      : unknown
    : unknown;

/**
 * Extract the default value type from a flag definition.
 */
export type FlagDefaultValue<K extends string> =
  K extends keyof FlagDefinitions
    ? FlagDefinitions[K] extends { defaultValue: infer D }
      ? D
      : undefined
    : unknown;

// ── Filtered key sets ──────────────────────────────────────────────────────

/** Union of flag keys with type 'boolean'. */
export type BooleanFlagKey = keyof FlagDefinitions extends never
  ? string
  : {
      [K in keyof FlagDefinitions]: FlagDefinitions[K] extends { type: 'boolean' }
        ? K
        : never;
    }[keyof FlagDefinitions] & string;

/** Union of flag keys with type 'string'. */
export type StringFlagKey = keyof FlagDefinitions extends never
  ? string
  : {
      [K in keyof FlagDefinitions]: FlagDefinitions[K] extends { type: 'string' }
        ? K
        : never;
    }[keyof FlagDefinitions] & string;

/** Union of flag keys with type 'number'. */
export type NumberFlagKey = keyof FlagDefinitions extends never
  ? string
  : {
      [K in keyof FlagDefinitions]: FlagDefinitions[K] extends { type: 'number' }
        ? K
        : never;
    }[keyof FlagDefinitions] & string;

/** Union of flag keys with type 'json'. */
export type JsonFlagKey = keyof FlagDefinitions extends never
  ? string
  : {
      [K in keyof FlagDefinitions]: FlagDefinitions[K] extends { type: 'json' }
        ? K
        : never;
    }[keyof FlagDefinitions] & string;

/** Union of flag keys with type 'multivariate'. */
export type MultivariateFlagKey = keyof FlagDefinitions extends never
  ? string
  : {
      [K in keyof FlagDefinitions]: FlagDefinitions[K] extends { type: 'multivariate' }
        ? K
        : never;
    }[keyof FlagDefinitions] & string;
